"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-09 12:01:40.748666
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=False),
    sa.Column('alternate_greetings_json', sa.Text(), nullable=False),
    sa.Column('example_dialogue', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('creator_notes', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('world_book_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('world_book_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_book_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('secondary_keywords_json', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('scan_depth', sa.Integer(), nullable=False),
    sa.Column('insertion_position', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('recursive', sa.Boolean(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_traces_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_traces_turn_id'), ['turn_id'], unique=False)

    op.create_table('character_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', name='uq_character_chat')
    )
    with op.batch_alter_table('character_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_profiles_chat_id'), ['chat_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)

    op.create_table('story_characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('source_template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=False),
    sa.Column('alternate_greetings_json', sa.Text(), nullable=False),
    sa.Column('example_dialogue', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('creator_notes', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('world_book_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['character_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_characters_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_characters_source_template_id'), ['source_template_id'], unique=False)

    op.create_table('story_personas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('source_template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('speaking_style', sa.Text(), nullable=False),
    sa.Column('world_book_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['persona_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', name='uq_story_persona_chat')
    )
    with op.batch_alter_table('story_personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_personas_chat_id'), ['chat_id'], unique=False)

    op.create_table('story_world_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('source_template_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('secondary_keywords_json', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('scan_depth', sa.Integer(), nullable=False),
    sa.Column('insertion_position', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('recursive', sa.Boolean(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['world_book_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_world_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_world_books_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_world_books_source_template_id'), ['source_template_id'], unique=False)

    op.create_table('world_book_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('secondary_keywords_json', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('constant', sa.Boolean(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('scan_depth', sa.Integer(), nullable=False),
    sa.Column('insertion_position', sa.String(length=30), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('recursive', sa.Boolean(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_book_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_book_entries_chat_id'), ['chat_id'], unique=False)

    op.create_table('audit_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_value_json', sa.Text(), nullable=True),
    sa.Column('actual_value_json', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_issues_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_issues_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_issues_status'), ['status'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_kind'), ['kind'], unique=False)

    op.create_table('message_bookmarks',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('message_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_bookmarks_chat_id'), ['chat_id'], unique=False)

    op.create_table('message_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('state_changes_json', sa.Text(), nullable=False),
    sa.Column('graph_events_json', sa.Text(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'position', name='uq_message_variant_position')
    )
    with op.batch_alter_table('message_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_variants_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_variants_message_id'), ['message_id'], unique=False)

    op.create_table('narrative_deltas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('user_message_id', sa.String(length=36), nullable=False),
    sa.Column('assistant_message_id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_message_id', name='uq_delta_assistant_message')
    )
    with op.batch_alter_table('narrative_deltas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrative_deltas_assistant_message_id'), ['assistant_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narrative_deltas_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narrative_deltas_user_message_id'), ['user_message_id'], unique=False)

    op.create_table('roleplay_graph_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roleplay_graph_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roleplay_graph_events_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roleplay_graph_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_roleplay_graph_events_source_message_id'), ['source_message_id'], unique=False)

    op.create_table('scene_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['scene_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_nodes_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_nodes_parent_id'), ['parent_id'], unique=False)

    op.create_table('state_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_changes_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_changes_status'), ['status'], unique=False)

    op.create_table('state_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'entity', 'key', name='uq_state_identity')
    )
    with op.batch_alter_table('state_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_entries_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_entries_entity'), ['entity'], unique=False)

    op.create_table('story_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_checkpoints_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_checkpoints_message_id'), ['message_id'], unique=False)

    op.create_table('timeline_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('story_time', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_anchors_chat_id'), ['chat_id'], unique=False)

    op.create_table('narrative_leaves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('user_message_id', sa.String(length=36), nullable=False),
    sa.Column('assistant_message_id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detail_mode', sa.String(length=20), nullable=False),
    sa.Column('time_start', sa.String(length=200), nullable=True),
    sa.Column('time_end', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_message_id', name='uq_narrative_leaf_message')
    )
    with op.batch_alter_table('narrative_leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrative_leaves_assistant_message_id'), ['assistant_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narrative_leaves_chat_id'), ['chat_id'], unique=False)

    op.create_table('narrative_summary_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('child_refs_json', sa.Text(), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=True),
    sa.Column('time_start', sa.String(length=200), nullable=True),
    sa.Column('time_end', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('narrative_summary_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrative_summary_nodes_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narrative_summary_nodes_level'), ['level'], unique=False)

    op.create_table('npcs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('relation_to_user', sa.Text(), nullable=False),
    sa.Column('relations_json', sa.Text(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('presence', sa.String(length=20), nullable=False),
    sa.Column('location_scene_id', sa.String(length=36), nullable=True),
    sa.Column('outfit', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_scene_id'], ['scene_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'name', name='uq_npc_chat_name')
    )
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npcs_chat_id'), ['chat_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npcs_chat_id'))

    op.drop_table('npcs')
    with op.batch_alter_table('narrative_summary_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrative_summary_nodes_level'))
        batch_op.drop_index(batch_op.f('ix_narrative_summary_nodes_chat_id'))

    op.drop_table('narrative_summary_nodes')
    with op.batch_alter_table('narrative_leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrative_leaves_chat_id'))
        batch_op.drop_index(batch_op.f('ix_narrative_leaves_assistant_message_id'))

    op.drop_table('narrative_leaves')
    with op.batch_alter_table('timeline_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_anchors_chat_id'))

    op.drop_table('timeline_anchors')
    with op.batch_alter_table('story_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_checkpoints_message_id'))
        batch_op.drop_index(batch_op.f('ix_story_checkpoints_chat_id'))

    op.drop_table('story_checkpoints')
    with op.batch_alter_table('state_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_entries_entity'))
        batch_op.drop_index(batch_op.f('ix_state_entries_chat_id'))

    op.drop_table('state_entries')
    with op.batch_alter_table('state_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_changes_status'))
        batch_op.drop_index(batch_op.f('ix_state_changes_chat_id'))

    op.drop_table('state_changes')
    with op.batch_alter_table('scene_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_scene_nodes_chat_id'))

    op.drop_table('scene_nodes')
    with op.batch_alter_table('roleplay_graph_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roleplay_graph_events_source_message_id'))
        batch_op.drop_index(batch_op.f('ix_roleplay_graph_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_roleplay_graph_events_chat_id'))

    op.drop_table('roleplay_graph_events')
    with op.batch_alter_table('narrative_deltas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrative_deltas_user_message_id'))
        batch_op.drop_index(batch_op.f('ix_narrative_deltas_chat_id'))
        batch_op.drop_index(batch_op.f('ix_narrative_deltas_assistant_message_id'))

    op.drop_table('narrative_deltas')
    with op.batch_alter_table('message_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_variants_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_variants_chat_id'))

    op.drop_table('message_variants')
    with op.batch_alter_table('message_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_bookmarks_chat_id'))

    op.drop_table('message_bookmarks')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_kind'))
        batch_op.drop_index(batch_op.f('ix_memories_chat_id'))

    op.drop_table('memories')
    with op.batch_alter_table('audit_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_issues_status'))
        batch_op.drop_index(batch_op.f('ix_audit_issues_message_id'))
        batch_op.drop_index(batch_op.f('ix_audit_issues_chat_id'))

    op.drop_table('audit_issues')
    with op.batch_alter_table('world_book_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_book_entries_chat_id'))

    op.drop_table('world_book_entries')
    with op.batch_alter_table('story_world_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_world_books_source_template_id'))
        batch_op.drop_index(batch_op.f('ix_story_world_books_chat_id'))

    op.drop_table('story_world_books')
    with op.batch_alter_table('story_personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_personas_chat_id'))

    op.drop_table('story_personas')
    with op.batch_alter_table('story_characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_characters_source_template_id'))
        batch_op.drop_index(batch_op.f('ix_story_characters_chat_id'))

    op.drop_table('story_characters')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))

    op.drop_table('messages')
    with op.batch_alter_table('character_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_profiles_chat_id'))

    op.drop_table('character_profiles')
    with op.batch_alter_table('agent_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_traces_turn_id'))
        batch_op.drop_index(batch_op.f('ix_agent_traces_chat_id'))

    op.drop_table('agent_traces')
    op.drop_table('world_book_templates')
    op.drop_table('persona_templates')
    op.drop_table('chats')
    op.drop_table('character_templates')
    # ### end Alembic commands ###
